[package]
name = "oqtopus-cli"
version = "0.0.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
libc = "0.2"
tempfile = "3"

[[bin]]
name = "oqtopus"
path = "src/main.rs"

[[test]]
name = "characterization"
path = "tests/characterization/main.rs"

[[test]]
name = "cli"
path = "tests/cli.rs"

[dev-dependencies]
insta = "1"
